extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_ci4_matt_granite_ci4[];
extern u8 bob_dl_ci4_matt_granite_ci4_pal_rgba16[];
extern u8 bob_dl_cloud_2_i8[];
extern Vtx bob_dl_blockout_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_blockout_mesh_layer_1_vtx_0[17];
extern Gfx bob_dl_blockout_mesh_layer_1_tri_0[];
extern Vtx bob_dl_blockout_mesh_layer_1_vtx_1[352];
extern Gfx bob_dl_blockout_mesh_layer_1_tri_1[];
extern Gfx mat_bob_dl_rocque[];
extern Gfx mat_revert_bob_dl_rocque[];
extern Gfx mat_bob_dl_cloud_NORMAL_layer1[];
extern Gfx mat_revert_bob_dl_cloud_NORMAL_layer1[];
extern Gfx bob_dl_blockout_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
